# Generated by Django 2.2.5 on 2019-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
