# Generated by Django 2.2.5 on 2019-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.NullBooleanField(default=False),
        ),
    ]
